services:
  - type: web
    name: todolist-app
    env: docker
    region: oregon
    plan: free
    branch: master
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: todolist-db
    databaseName: todolist
    user: todolist_user
    region: oregon
    plan: free
