services:
  - type: web
    name: todolist-app
    env: docker
    region: oregon
    plan: free
    branch: master
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8080
