# Configuração padrão - H2 Database
spring:
  application:
    name: todolist
  datasource:
    url: jdbc:h2:mem:todolist
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

# Server configuration
server:
  port: ${PORT:8080}

# =============================================================================
# CONFIGURAÇÕES POSTGRESQL (COMENTADAS - DESCOMENTE PARA USAR)
# =============================================================================

# ---
# # Configuração para PostgreSQL local
# spring:
#   config:
#     activate:
#       on-profile: local-postgres
#   datasource:
#     url: jdbc:postgresql://localhost:5432/todolist
#     username: postgres
#     password: 123456
#     driver-class-name: org.postgresql.Driver
#   jpa:
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     hibernate:
#       ddl-auto: update

# ---
# # Configuração para produção (PostgreSQL no Render)
# spring:
#   config:
#     activate:
#       on-profile: prod
#   datasource:
#     url: ${DATABASE_URL}
#     driver-class-name: org.postgresql.Driver
#   jpa:
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     hibernate:
#       ddl-auto: update
