name: Simple Docker Build

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Debug - List files
        run: |
          echo "Current directory:"
          pwd
          echo "Files in root:"
          ls -la
          echo "Looking for Dockerfile:"
          find . -name "Dockerfile" -type f 2>/dev/null || echo "Dockerfile not found"
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t eddiecps/todolist-app:latest .
          docker push eddiecps/todolist-app:latest
